/* Parity test: the app's live OFF->score port (Tier-2 scan) must MATCH pipeline/scoring.py exactly,
   else a live verdict would disagree with a baked one (dishonest). offScore below is copied verbatim
   from app/app.js; the same mock is scored in Python (see the shell runner) and compared. */
const e = require('../app/engine.js');
const fs = require('fs');
const path = require('path');

const OFF_GRADE={a:100,b:75,c:50,d:25,e:0}, OFF_NOVA={1:100,2:66,3:33,4:0};
const OFF_ETHICAL={'en:organic':1,'en:eu-organic':1,'en:usda-organic':1,'en:fairtrade':1,'en:fair-trade':1,'en:fairtrade-international':1,'en:rainforest-alliance':1};
const OFF_TAGMAP={'en:nuts':'nuts','en:tree-nuts':'nuts','en:peanuts':'peanut','en:soybeans':'soy','en:soya':'soy','en:soy':'soy','en:gluten':'gluten'};
const FOOD_CRITERIA=[
  {key:'environment',label:'Environment',tier:'measured'},{key:'processing',label:'Processing',tier:'measured'},
  {key:'nutrition_grade',label:'Nutrition',tier:'measured'},{key:'protein',label:'Protein',tier:'measured'},
  {key:'low_sugar',label:'Low sugar',tier:'measured'},{key:'ethics',label:'Ethics',tier:'certified'}];
function _offnum(v){const f=parseFloat(v);return isNaN(f)?null:f;}
function offScore(p,code){
  const name=(p.product_name||'').trim(); if(!name)return null;
  const nutr=p.nutriments||{};
  const eco=p.ecoscore_grade||p.environmental_score_grade;
  const eg=((eco&&eco!=='unknown'&&eco!=='not-applicable')?String(eco):'').toLowerCase();
  const g=String(p.nutriscore_grade||'').toLowerCase(), nova=p.nova_group;
  const protein=_offnum(nutr.proteins_100g), sugar=_offnum(nutr.sugars_100g);
  const labels=p.labels_tags||[]; let n_eth=0; for(const l of labels)if(OFF_ETHICAL[l])n_eth++;
  const scores={
    environment: OFF_GRADE[eg]!=null?OFF_GRADE[eg]:null,
    processing: (typeof nova==='number'&&OFF_NOVA[nova]!=null)?OFF_NOVA[nova]:null,
    nutrition_grade: OFF_GRADE[g]!=null?OFF_GRADE[g]:null,
    protein: protein==null?null:Math.min(100,Math.round(protein*12.5)),
    low_sugar: sugar==null?null:Math.max(0,Math.min(100,Math.round(100-sugar*4))),
    ethics: labels.length?Math.min(100,n_eth*50):null
  };
  let nn=0; for(const k in scores)if(scores[k]!=null)nn++;
  if(nn<2)return null;
  return {code:code,name:name.slice(0,60),brand:((p.brands||'').split(',')[0]||'').slice(0,30),scores:scores};
}

const MOCK={product_name:'Test Oat Bar',brands:'TestCo',nutriscore_grade:'b',ecoscore_grade:'c',nova_group:4,
  nutriments:{proteins_100g:6.0,sugars_100g:10.0},labels_tags:['en:organic','en:vegan'],
  allergens_tags:['en:gluten'],traces_tags:['en:nuts'],code:'1234567890123'};

const rec=offScore(MOCK,'1234567890123');
const ks=Object.keys(rec.scores).sort(), sorted={}; ks.forEach(k=>sorted[k]=rec.scores[k]);
console.log('JS '+JSON.stringify(sorted));

// and the verdict computes through the real engine (what renderLiveVerdict does)
const tw={planet:5,people:5,health:5,honesty:3,privacy:3,animals:3,cost:3,local:3};
const w=e.themeDefaults(FOOD_CRITERIA, tw, e.KEY2THEME);
const V=e.verdict(rec,{criteria:FOOD_CRITERIA,weights:w});
console.log('VERDICT '+(V?V.score+' '+V.tier[0]+' | reason:'+(V.reason&&V.reason.label):'null'));

// H20 split-mode handoff. These fixtures are generated by the same Python
// helper that builds the three pilot datasets. The running app remains on the
// legacy scorer until app/design consumes this category-aware contract.
const index=JSON.parse(fs.readFileSync(path.join(__dirname,'..','app','data','index.json'),'utf8'));
const contract=index.certificationScoringContract;
if(!contract||contract.status!=='h20-app-owned-certification-scoring-parity')throw new Error('missing H20 certification scoring contract');
function contractCertificationScores(labels){
  if(!labels||!labels.length)return Object.fromEntries(contract.criteria.map(row=>[row.key,null]));
  const present=new Set(labels);
  return Object.fromEntries(contract.criteria.map(row=>[
    row.key,
    row.acceptedTags.some(tag=>present.has(tag))?row.scoreWhenMatched:row.scoreWhenLabelsPresentWithoutMatch
  ]));
}
for(const fixture of contract.fixtures||[]){
  const actual=contractCertificationScores(fixture.labels);
  if(JSON.stringify(actual)!==JSON.stringify(fixture.expectedScores)){
    throw new Error(`H20 certification fixture ${fixture.id} drifted`);
  }
}
console.log(`CERTIFICATION CONTRACT ${(contract.fixtures||[]).length} fixtures pass; app-side H20 parity remains open`);
