#!/usr/bin/env node
/* Build the implementation-ready presentation package.

   Authored copy stays under content/presentation. The public taxonomy comes
   from the schema-validated ontology and is resolved here so app code never
   has to interpret selectors or infer missing states.
*/
'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const STRINGS_SOURCE = path.join(ROOT, 'content', 'presentation', 'strings.json');
const PAGE_KINDS_SOURCE = path.join(ROOT, 'content', 'presentation', 'page-kinds.json');
const FIXTURES_SOURCE = path.join(ROOT, 'content', 'presentation', 'fixtures.json');
const SOURCE_INDEX_SOURCE = path.join(ROOT, 'content', 'presentation', 'sources.json');
const ONTOLOGY_SOURCE = path.join(ROOT, 'content', 'ontology.json');
const INDEX_SOURCE = path.join(ROOT, 'app', 'data', 'index.json');
const OUTPUT = path.join(ROOT, 'app', 'data', 'presentation.json');
const SCRIPT_OUTPUT = path.join(ROOT, 'app', 'presentation-data.js');
const EXPECTED_PAGE_KINDS = [
  'entry',
  'category',
  'value',
  'source',
  'company-brand',
  'guide',
  'task',
  'file',
  'changes',
  'commons-governance',
];

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function formatJson(value) {
  return JSON.stringify(value, null, 2) + '\n';
}

function formatScript(value) {
  const json = JSON.stringify(value).replace(/<\/script/gi, '<\\/script');
  return `/* Generated by pipeline/build_presentation.js. Do not edit. */\nwindow.CC_PRESENTATION=${json};\n`;
}

function assert(condition, message) {
  if (!condition) throw new Error(message);
}

function slug(value) {
  return String(value || '')
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function duplicateValues(values) {
  const seen = new Set();
  const duplicates = new Set();
  for (const value of values) {
    if (seen.has(value)) duplicates.add(value);
    seen.add(value);
  }
  return [...duplicates];
}

function validateStrings(source) {
  assert(source.format === 'open-values-presentation-strings', 'strings.json: unexpected format');
  assert(source.version === '1.0.0', 'strings.json: expected version 1.0.0');
  assert(source.locale === 'en', 'strings.json: expected locale en');

  const vocabulary = source.signedVocabulary || {};
  const expectedVocabulary = {
    personalRules: 'My rules',
    sharedBaseline: 'The baseline',
    tasks: 'Tasks',
    file: 'Your file',
    closeCallPriorities: 'Close-call priorities',
  };
  assert(JSON.stringify(vocabulary) === JSON.stringify(expectedVocabulary), 'strings.json: signed vocabulary changed');

  const coverage = source.coverage || {};
  const coverageLabels = Object.values(coverage).map((state) => state.label);
  const expectedCoverage = [
    'Sources cover this answer',
    'Some evidence is missing',
    'Not enough evidence to rank',
    'Not yet covered',
    'Could not load this source',
  ];
  assert(JSON.stringify(coverageLabels) === JSON.stringify(expectedCoverage), 'strings.json: coverage labels changed');
  for (const [id, state] of Object.entries(coverage)) {
    assert(typeof state.sentence === 'string' && state.sentence.trim(), `strings.json: coverage.${id}.sentence missing`);
    assert(typeof state.action === 'string' && state.action.trim(), `strings.json: coverage.${id}.action missing`);
  }

  const evidenceKinds = Object.values(source.evidenceKinds || {});
  assert(JSON.stringify(evidenceKinds) === JSON.stringify(['Measured', 'Certified', 'Assessed from public evidence']), 'strings.json: evidence labels changed');
  const templates = source.appliedValues && source.appliedValues.templates || {};
  assert(Object.keys(templates).length === 6, `strings.json: expected 6 explanation templates, found ${Object.keys(templates).length}`);
  assert(source.appliedValues.label === 'Why this answer', 'strings.json: applied-values label must be Why this answer');
}

function validatePageKinds(source) {
  assert(source.format === 'open-values-presentation-page-kinds', 'page-kinds.json: unexpected format');
  assert(source.version === '1.0.0', 'page-kinds.json: expected version 1.0.0');
  assert(Array.isArray(source.pageKinds), 'page-kinds.json: pageKinds must be an array');
  assert(JSON.stringify(source.pageKinds.map((page) => page.id)) === JSON.stringify(EXPECTED_PAGE_KINDS), 'page-kinds.json: page kind ids or order changed');

  for (const page of source.pageKinds) {
    assert(typeof page.label === 'string' && page.label.trim(), `${page.id}: label missing`);
    assert(typeof page.purpose === 'string' && page.purpose.trim(), `${page.id}: purpose missing`);
    assert(typeof page.mainAction === 'string' && page.mainAction.trim(), `${page.id}: mainAction missing`);
    assert(Array.isArray(page.sections) && page.sections.length >= 6, `${page.id}: expected at least 6 ordered sections`);
    assert(duplicateValues(page.sections.map((section) => section.id)).length === 0, `${page.id}: duplicate section id`);
    for (const section of page.sections) {
      assert(/^[a-z][a-z0-9-]*$/.test(section.id || ''), `${page.id}: invalid section id ${section.id || '(missing)'}`);
      assert(typeof section.heading === 'string' && section.heading.trim(), `${page.id}/${section.id}: heading missing`);
      assert(['required', 'applicable', 'ranked-or-filtered', 'available', 'optional'].includes(section.when), `${page.id}/${section.id}: invalid applicability ${section.when}`);
    }
    assert(page.stateCopy && typeof page.stateCopy.rich === 'string', `${page.id}: rich state copy missing`);
    assert(page.stateCopy && typeof page.stateCopy.thin === 'string', `${page.id}: thin state copy missing`);
    assert(page.stateCopy && typeof page.stateCopy.notCovered === 'string', `${page.id}: not-covered state copy missing`);
  }
}

function valueAtPath(value, dotted) {
  return String(dotted || '').split('.').filter(Boolean).reduce((current, key) => current && current[key], value);
}

function validateSourceRef(ref, fixtureId) {
  assert(ref && typeof ref.path === 'string' && ref.path.trim(), `${fixtureId}: source ref path missing`);
  const absolute = path.resolve(ROOT, ref.path);
  assert(absolute.startsWith(`${ROOT}${path.sep}`), `${fixtureId}: source ref leaves repository`);
  assert(fs.existsSync(absolute), `${fixtureId}: source ref missing ${ref.path}`);
  const text = fs.readFileSync(absolute, 'utf8');
  if (ref.contains != null) {
    assert(typeof ref.contains === 'string' && ref.contains, `${fixtureId}: source ref contains must be non-empty`);
    assert(text.includes(ref.contains), `${fixtureId}: ${ref.path} does not contain ${ref.contains}`);
  }
  if (ref.collection != null) {
    assert(ref.path.endsWith('.json'), `${fixtureId}: collection source must be JSON`);
    const data = JSON.parse(text);
    const collection = valueAtPath(data, ref.collection);
    if (ref.key != null) {
      assert(collection && !Array.isArray(collection) && Object.prototype.hasOwnProperty.call(collection, ref.key), `${fixtureId}: ${ref.path} ${ref.collection}.${ref.key} missing`);
    } else {
      assert(Array.isArray(collection), `${fixtureId}: ${ref.path} ${ref.collection} must be an array`);
      assert(ref.match && typeof ref.match.field === 'string', `${fixtureId}: collection match missing`);
      assert(collection.some((item) => item && item[ref.match.field] === ref.match.equals), `${fixtureId}: ${ref.path} ${ref.collection} has no ${ref.match.field}=${ref.match.equals}`);
    }
  }
}

function validateFixtures(source, strings, pageKinds) {
  assert(source.format === 'open-values-presentation-fixtures', 'fixtures.json: unexpected format');
  assert(source.version === '1.0.0', 'fixtures.json: expected version 1.0.0');
  const states = ['rich', 'thin', 'not-yet-covered'];
  assert(JSON.stringify(source.states) === JSON.stringify(states), 'fixtures.json: state order changed');
  assert(Array.isArray(source.fixtureSets), 'fixtures.json: fixtureSets must be an array');
  assert(JSON.stringify(source.fixtureSets.map((set) => set.pageKind)) === JSON.stringify(EXPECTED_PAGE_KINDS), 'fixtures.json: page kind ids or order changed');

  const pageById = new Map(pageKinds.pageKinds.map((page) => [page.id, page]));
  const ids = [];
  for (const set of source.fixtureSets) {
    assert(Array.isArray(set.cases) && set.cases.length === 3, `${set.pageKind}: expected exactly 3 fixtures`);
    assert(JSON.stringify(set.cases.map((fixture) => fixture.state)) === JSON.stringify(states), `${set.pageKind}: expected rich, thin, and not-yet-covered fixtures in order`);
    for (const fixture of set.cases) {
      ids.push(fixture.id);
      assert(/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(fixture.id || ''), `${set.pageKind}: invalid fixture id ${fixture.id || '(missing)'}`);
      assert(typeof fixture.title === 'string' && fixture.title.trim(), `${fixture.id}: title missing`);
      assert(fixture.instance == null || ['conscious-consuming', 'kosplora'].includes(fixture.instance), `${fixture.id}: invalid instance`);
      assert(/^#[a-z0-9][^\s]*$/.test(fixture.route || ''), `${fixture.id}: invalid route`);
      assert(Array.isArray(fixture.sourceRefs) && fixture.sourceRefs.length, `${fixture.id}: sourceRefs missing`);
      fixture.sourceRefs.forEach((ref) => validateSourceRef(ref, fixture.id));
      const expected = fixture.expected || {};
      const coverageKey = fixture.state === 'not-yet-covered' ? 'notCovered' : fixture.state;
      assert(expected.coverage === strings.coverage[coverageKey].label, `${fixture.id}: coverage string differs from signed table`);
      assert(typeof expected.action === 'string' && expected.action.trim(), `${fixture.id}: expected action missing`);
      assert(Array.isArray(expected.path) && expected.path.length, `${fixture.id}: expected path missing`);
      assert(Array.isArray(expected.mustShow) && expected.mustShow.length >= 3, `${fixture.id}: expected mustShow needs at least 3 strings`);
      assert(Array.isArray(expected.mustNotClaim) && expected.mustNotClaim.length, `${fixture.id}: expected mustNotClaim missing`);
      assert(Array.isArray(fixture.requirements) && fixture.requirements.length, `${fixture.id}: requirement receipts missing`);
      assert(fixture.requirements.every((id) => /^R-[A-Z]+-\d{2}$/.test(id)), `${fixture.id}: invalid requirement id`);
      if (fixture.state !== 'not-yet-covered') {
        assert(expected.action === pageById.get(set.pageKind).mainAction, `${fixture.id}: action differs from page-kind main action`);
      }
    }
  }
  assert(ids.length === 30, `fixtures.json: expected 30 fixtures, found ${ids.length}`);
  assert(duplicateValues(ids).length === 0, `fixtures.json: duplicate fixture ids ${duplicateValues(ids).join(', ')}`);
}

function validateSourceIndex(source, index) {
  assert(source.format === 'open-values-presentation-source-index', 'sources.json: unexpected format');
  assert(source.version === '1.0.0', 'sources.json: expected version 1.0.0');
  assert(typeof source.scope === 'string' && source.scope.trim(), 'sources.json: scope missing');
  assert(Array.isArray(source.records) && source.records.length >= 2, 'sources.json: expected at least 2 canonical records');
  assert(duplicateValues(source.records.map((record) => record.id)).length === 0, 'sources.json: duplicate source id');
  const categoryById = new Map((index.categories || []).map((category) => [category.id, category]));
  for (const record of source.records) {
    assert(/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(record.id || ''), `sources.json: invalid source id ${record.id || '(missing)'}`);
    assert(typeof record.title === 'string' && record.title.trim(), `${record.id}: title missing`);
    assert(typeof record.publisher === 'string' && record.publisher.trim(), `${record.id}: publisher missing`);
    assert(/^https:\/\//.test(record.url || ''), `${record.id}: HTTPS source URL missing`);
    assert(/^\d{4}-\d{2}-\d{2}$/.test(record.published || ''), `${record.id}: published date missing`);
    assert(/^\d{4}-\d{2}-\d{2}$/.test(record.reviewed || ''), `${record.id}: reviewed date missing`);
    assert(typeof record.scope === 'string' && record.scope.trim(), `${record.id}: scope missing`);
    assert(record.method === null || (typeof record.method === 'string' && record.method.trim()), `${record.id}: method must be text or null`);
    assert(Array.isArray(record.limits) && record.limits.length, `${record.id}: limits missing`);
    assert(Array.isArray(record.supportedClaims) && record.supportedClaims.length, `${record.id}: supportedClaims missing`);
    for (const claim of record.supportedClaims) {
      const category = categoryById.get(claim.category);
      assert(category, `${record.id}: unknown claim category ${claim.category}`);
      const dataset = readJson(path.join(ROOT, 'app', 'data', category.file));
      const entries = dataset.products || dataset.resources || [];
      const entry = entries.find((item) => item.code === claim.entry);
      assert(entry, `${record.id}: unknown claim entry ${claim.category}/${claim.entry}`);
      const receipt = entry.provenance && entry.provenance[claim.criterion];
      assert(receipt && typeof receipt === 'object' && receipt.source === record.url, `${record.id}: ${claim.entry}.${claim.criterion} does not cite the canonical URL`);
    }
  }
}

function selectorMatches(row, selector) {
  if (row.domain !== selector.domain) return false;
  if (selector.groups && !selector.groups.includes(row.group)) return false;
  if (selector.labels && !selector.labels.includes(row.label)) return false;
  return true;
}

function sourceRows(ontology) {
  const rows = [];
  for (const domain of ontology.domains || []) {
    for (const row of domain.categories || []) rows.push({ ...row, domain: domain.label });
  }
  return rows;
}

function matches(row, category, subcategory) {
  return row.need === category.need
    && (subcategory.selectors || []).some((selector) => selectorMatches(row, selector));
}

function routeFor(row) {
  if (!row.cid) return `#not-yet-covered/${slug(row.label)}`;
  if (row.facet) return `#decide/${row.cid}/${encodeURIComponent(row.facet)}`;
  return `#decide/${row.cid}`;
}

function resolvedTaxonomy(ontology, index) {
  const presentation = ontology.presentation || {};
  const rows = sourceRows(ontology);
  const decisions = [];
  const needs = [];

  for (const need of ontology.needs || []) {
    const needNode = {
      id: need.id,
      label: need.label,
      reads: need.reads,
      categories: [],
    };
    for (const category of (presentation.categories || []).filter((item) => item.need === need.id)) {
      const categoryNode = {
        id: category.id,
        label: category.label,
        reads: category.reads,
        subcategories: [],
      };
      for (const subcategory of category.subcategories || []) {
        const members = rows.filter((row) => matches(row, category, subcategory));
        const decisionIds = [];
        for (const row of members) {
          const id = row.cid
            ? (row.facet ? `${row.cid}:${slug(row.facet)}` : row.cid)
            : slug(row.label);
          decisionIds.push(id);
          const decision = {
            id,
            label: row.label,
            state: row.cid ? 'live' : 'not-yet-covered',
            route: routeFor(row),
            need: need.id,
            category: category.id,
            subcategory: subcategory.id,
            type: row.type,
            sourceDomain: row.domain,
            sourceGroup: row.group,
          };
          if (row.cid) decision.cid = row.cid;
          if (row.facet) decision.facet = row.facet;
          decisions.push(decision);
        }
        categoryNode.subcategories.push({
          id: subcategory.id,
          label: subcategory.label,
          decisionIds,
        });
      }
      needNode.categories.push(categoryNode);
    }
    needs.push(needNode);
  }

  const live = decisions.filter((decision) => decision.state === 'live');
  const gaps = decisions.filter((decision) => decision.state === 'not-yet-covered');
  const liveIds = new Set(live.map((decision) => decision.cid));
  const generatedIds = new Set((index.categories || []).map((category) => category.id));

  assert(needs.length === 8, `taxonomy: expected 8 needs, found ${needs.length}`);
  assert(needs.reduce((sum, need) => sum + need.categories.length, 0) === 18, 'taxonomy: expected 18 categories');
  assert(needs.flatMap((need) => need.categories).reduce((sum, category) => sum + category.subcategories.length, 0) === 39, 'taxonomy: expected 39 subcategories');
  assert(decisions.length === 206, `taxonomy: expected 206 decisions, found ${decisions.length}`);
  assert(live.length === 96, `taxonomy: expected 96 live paths, found ${live.length}`);
  assert(liveIds.size === 88, `taxonomy: expected 88 live datasets, found ${liveIds.size}`);
  assert(gaps.length === 110, `taxonomy: expected 110 gaps, found ${gaps.length}`);
  assert(duplicateValues(decisions.map((decision) => decision.id)).length === 0, 'taxonomy: duplicate decision id');
  assert(duplicateValues(decisions.map((decision) => decision.route)).length === 0, 'taxonomy: duplicate decision route');
  assert([...liveIds].every((id) => generatedIds.has(id)) && [...generatedIds].every((id) => liveIds.has(id)), 'taxonomy: generated category set disagrees with resolved live datasets');

  return {
    source: 'content/ontology.json',
    sourceSchema: 'app/data/standard/schemas/ontology.schema.json',
    generatedSource: 'app/data/index.json#/ontology/presentation',
    version: presentation.version,
    levels: presentation.levels,
    leafState: presentation.leafState,
    counts: {
      needs: needs.length,
      categories: needs.reduce((sum, need) => sum + need.categories.length, 0),
      subcategories: needs.flatMap((need) => need.categories).reduce((sum, category) => sum + category.subcategories.length, 0),
      decisions: decisions.length,
      livePaths: live.length,
      liveDatasets: liveIds.size,
      notYetCovered: gaps.length,
    },
    needs,
    decisions,
  };
}

function buildPackage() {
  const strings = readJson(STRINGS_SOURCE);
  const pageKinds = readJson(PAGE_KINDS_SOURCE);
  const fixtures = readJson(FIXTURES_SOURCE);
  const sourceIndex = readJson(SOURCE_INDEX_SOURCE);
  const ontology = readJson(ONTOLOGY_SOURCE);
  const index = readJson(INDEX_SOURCE);

  validateStrings(strings);
  validatePageKinds(pageKinds);
  validateFixtures(fixtures, strings, pageKinds);
  validateSourceIndex(sourceIndex, index);
  assert(JSON.stringify(index.ontology) === JSON.stringify(ontology), 'app/data/index.json ontology differs from content/ontology.json');

  const payload = {
    format: 'open-values-presentation-package',
    version: '1.0.0',
    built: strings.updated,
    consumer: 'P5 presentation implementation',
    sources: [
      'content/ontology.json',
      'content/presentation/strings.json',
      'content/presentation/page-kinds.json',
      'content/presentation/fixtures.json',
      'content/presentation/sources.json',
    ],
    taxonomy: resolvedTaxonomy(ontology, index),
    strings: {
      locale: strings.locale,
      signedVocabulary: strings.signedVocabulary,
      search: strings.search,
      objectTypes: strings.objectTypes,
      coverage: strings.coverage,
      fieldStates: strings.fieldStates,
      evidenceKinds: strings.evidenceKinds,
      appliedValues: strings.appliedValues,
      actions: strings.actions,
      errors: strings.errors,
    },
    pageKinds: pageKinds.pageKinds,
    fixtures: fixtures.fixtureSets,
    sourceIndex: {
      scope: sourceIndex.scope,
      records: sourceIndex.records,
    },
  };
  payload.checksum = `sha256:${crypto.createHash('sha256').update(JSON.stringify(payload)).digest('hex')}`;
  return payload;
}

function writeOutput(value) {
  fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
  fs.writeFileSync(OUTPUT, formatJson(value));
  fs.writeFileSync(SCRIPT_OUTPUT, formatScript(value));
}

function checkOutput(value) {
  const drift = [];
  if (!fs.existsSync(OUTPUT)) drift.push('app/data/presentation.json is missing');
  else if (fs.readFileSync(OUTPUT, 'utf8') !== formatJson(value)) drift.push('app/data/presentation.json');
  if (!fs.existsSync(SCRIPT_OUTPUT)) drift.push('app/presentation-data.js is missing');
  else if (fs.readFileSync(SCRIPT_OUTPUT, 'utf8') !== formatScript(value)) drift.push('app/presentation-data.js');
  return drift;
}

function main() {
  try {
    const value = buildPackage();
    if (process.argv.includes('--check')) {
      const drift = checkOutput(value);
      if (drift.length) {
        console.log('build_presentation: generated output is stale');
        for (const item of drift) console.log(`  ${item}`);
        process.exit(1);
      }
      console.log(`build_presentation: output current (${value.taxonomy.counts.decisions} decisions, ${value.pageKinds.length} page kinds, ${value.fixtures.flatMap((set) => set.cases).length} fixtures)`);
      return;
    }
    writeOutput(value);
    console.log(`build_presentation: wrote JSON + file-mode fallback (${value.taxonomy.counts.decisions} decisions, ${value.pageKinds.length} page kinds, ${value.fixtures.flatMap((set) => set.cases).length} fixtures)`);
  } catch (error) {
    console.error(`build_presentation FAILED: ${error.message}`);
    process.exit(1);
  }
}

if (require.main === module) main();

module.exports = {
  OUTPUT,
  SCRIPT_OUTPUT,
  buildPackage,
  formatJson,
  formatScript,
};
