#!/usr/bin/env node
/* Build app/lines.js (the line registry, as a plain script the app reads offline) from the canonical
   content/lines.json. Same generated-from-content pattern as data.js / guides.js — never hand-edit
   app/lines.js. Run standalone (node pipeline/build_lines.js) or via the build pipeline. */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SRC = path.join(ROOT, 'content', 'lines.json');
const OUT = path.join(ROOT, 'app', 'lines.js');

function build() {
  const reg = JSON.parse(fs.readFileSync(SRC, 'utf8'));
  const lines = Array.isArray(reg.lines) ? reg.lines : [];
  const sets = Array.isArray(reg.sets) ? reg.sets : [];
  const caps = reg.caps || { status: 'deferred' };
  const selection = reg.portableSelection || null;
  const body =
    '/* GENERATED by pipeline/build_lines.js from content/lines.json — do not hand-edit. */\n' +
    '(function (root) {\n' +
    '  root.CC = root.CC || {};\n' +
    '  root.CC.LINE_REGISTRY = ' + JSON.stringify(lines) + ';\n' +
    '  root.CC.LINE_SETS = ' + JSON.stringify(sets) + ';\n' +
    '  root.CC.LINE_SELECTION = ' + JSON.stringify(selection) + ';\n' +
    '  root.CC.LINE_CAPS = ' + JSON.stringify(caps) + ';\n' +
    '  root.CC.LINE_VERSION = ' + JSON.stringify(reg.version || '0.2') + ';\n' +
    '})(typeof self !== "undefined" ? self : this);\n';
  fs.writeFileSync(OUT, body);
  return { lines: lines.length, sets: sets.length };
}

if (require.main === module) {
  try {
    const counts = build();
    console.log('build_lines: wrote app/lines.js (' + counts.lines + ' lines, ' + counts.sets + ' sets)');
  } catch (e) {
    console.error('build_lines FAILED:', e.message);
    process.exit(1);
  }
}
module.exports = { build };
